apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: atlassian-bamboo
  name: atlassian-bamboo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlassian-bamboo
  template:
    metadata:
      labels:
        app: atlassian-bamboo
    spec:
      containers:
        - name: atlassian-bamboo
          image: atlassian/bamboo-server
          imagePullPolicy: Always
          volumeMounts:
          - name: bamboo-workdir
            mountPath: /var/atlassian/application-data/bamboo
          - name: bamboo-logs
            mountPath: /opt/atlassian/bamboo/logs
          ports:
          - containerPort: 8085
            name: http
            protocol: TCP
          - containerPort: 54663
            name: ssh
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 6
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: bamboo-workdir
          emptyDir: {}
        - name: bamboo-logs
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: atlassian-bamboo
  labels:
    app: atlassian-bamboo
spec:
  selector:
    app: atlassian-bamboo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8085
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  name: bamboo-ingress
spec:
  rules:
  - host: bamboo.k8s-srini.s3labs.com
    http:
      paths:
      - backend:
          serviceName: atlassian-bamboo
          servicePort: 80
        path: /
  tls:
  - hosts:
    - bamboo.k8s-srini.s3labs.com
    secretName: bamboo-ingress    