apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jira-software
  name: jira-software
  namespace: atlassian-jira
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi