apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: confluence
  name: confluence
  namespace: atlassian-confluence
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi